FROM openjdk:8-jdk-alpine 

WORKDIR /app/

COPY target/IplFantasyLeague-0.0.1-SNAPSHOT.jar/app/.IplFantasyLeague-0.0.1-SNAPSHOT.jar

EXPOSE 8080  

ENTRYPOINT ["java", "-jar", "/IplFantasyLeague-0.0.1-SNAPSHOT.jar"]