FROM openjdk:8-jdk-alpine

COPY target/IplFantasyLeague-0.0.1-SNAPSHOT.jar IplFantasyLeague-0.0.1-SNAPSHOT.jar

EXPOSE 8080  

ENTRYPOINT ["java", "-jar", "/IplFantasyLeague-0.0.1-SNAPSHOT.jar"]